FROM nodered/node-red:latest

RUN sudo npm install node-red-contrib-amqp-ack
RUN sudo npm install node-red-dashboard
RUN sudo npm install node-red-contrib-web-worldmap
RUN sudo npm install node-red-contrib-chartjs
RUN sudo npm install node-red-contrib-graphs

